allow to execute sql script
padok-team/terraform-google-sql pull request #75
Opened 2024-11-14 10:47 UTC by DamienJabs

2024-11-18 09:51 UTC, DamienJabs commented
Random selection zone was removed because of this error 

│ Error: Invalid count argument
│ 
│   on .terraform/modules/my-public-postgresql-db.postgresql-db/modules/postgresql/read_replica.tf line 26, in data "google_compute_zones" "available":
│   26:   count   = var.zone == null ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
╵

2024-11-19 10:40 UTC, Laudenlaruto requested changes

2024-11-19 10:40 UTC, Laudenlaruto commented on modules/encryption/main.tf
> +    prevent_destroy = false
C'est risqué ça

2024-11-29 13:23 UTC, Laudenlaruto approved these changes

2024-11-29 13:34 UTC, merged